# Windows twin of extract-frames.sh. Needs ffmpeg and ffprobe on PATH.
#
#   .\higgsfield\extract-frames.ps1 -Clips C:\path\to\clips [-Count 96] [-Width 1280]
param(
  [Parameter(Mandatory = $true)][string]$Clips,
  [int]$Count = 96,
  [int]$Width = 1280
)
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Out = Join-Path $Root "frames"
$Tmp = Join-Path ([IO.Path]::GetTempPath()) ("fs-frames-" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $Tmp | Out-Null

foreach ($bin in "ffmpeg", "ffprobe") {
  if (-not (Get-Command $bin -ErrorAction SilentlyContinue)) { throw "$bin not found. Install ffmpeg: https://ffmpeg.org/download.html" }
}

$clipFiles = Get-ChildItem -Path $Clips -Filter *.mp4 | Sort-Object Name
if ($clipFiles.Count -eq 0) { throw "no .mp4 files in $Clips" }
$list = Join-Path $Tmp "list.txt"
$clipFiles | ForEach-Object { "file '" + ($_.FullName -replace "\\", "/") + "'" } | Set-Content -Path $list -Encoding ascii
$master = Join-Path $Tmp "master.mp4"
& ffmpeg -y -loglevel error -f concat -safe 0 -i $list -c:v libx264 -pix_fmt yuv420p -an $master

$dur = [double](& ffprobe -v error -show_entries format=duration -of csv=p=0 $master)
$fps = [math]::Round($Count / $dur, 6)

New-Item -ItemType Directory -Path $Out -Force | Out-Null
Get-ChildItem -Path $Out -Filter "frame_*.jpg" | Remove-Item
& ffmpeg -y -loglevel error -i $master -vf "fps=$fps,scale=$($Width):-2" -frames:v $Count -q:v 3 (Join-Path $Out "frame_%04d.jpg")

$n = (Get-ChildItem -Path $Out -Filter "frame_*.jpg").Count
Copy-Item (Join-Path $Out "frame_0001.jpg") (Join-Path $Out "poster.jpg") -Force
$wh = (& ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0 (Join-Path $Out "frame_0001.jpg")) -split ","

@"
// Generated by higgsfield/extract-frames.ps1 from $(Split-Path -Leaf $Clips) (${dur}s).
window.FRESH_FRAMES = { count: $n, dir: "frames", pattern: "frame_{n}.jpg", pad: 4, width: $($wh[0]), height: $($wh[1]), focal: 0.6 };
"@ | Set-Content -Path (Join-Path $Out "manifest.js") -Encoding utf8

Remove-Item -Recurse -Force $Tmp
Write-Host "wrote $n frames ($($wh[0])x$($wh[1])) to $Out"
