#!/usr/bin/env bash
# Turn the four Higgsfield clips into the frame sequence the stage scrubs.
#
#   higgsfield/extract-frames.sh <clips-dir> [count] [width]
#
# <clips-dir>  folder holding clip-01.mp4 ... clip-04.mp4 (sorted by name)
# [count]      frames to sample across the full duration, default 96
# [width]      output width in px, default 1280 (height keeps aspect)
#
# Writes frames/frame_0001.jpg ..., frames/poster.jpg and frames/manifest.js,
# replacing whatever is there (the placeholder set included).
set -euo pipefail

CLIPS="${1:?usage: extract-frames.sh <clips-dir> [count] [width]}"
COUNT="${2:-96}"
WIDTH="${3:-1280}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/frames"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

for bin in ffmpeg ffprobe; do
  command -v "$bin" >/dev/null 2>&1 || { echo "$bin not found. Install ffmpeg: https://ffmpeg.org/download.html"; exit 1; }
done

# 1. Concatenate the clips in name order into one master.
: > "$TMP/list.txt"
for f in "$CLIPS"/*.mp4; do
  printf "file '%s'\n" "$(cd "$(dirname "$f")" && pwd)/$(basename "$f")" >> "$TMP/list.txt"
done
[ -s "$TMP/list.txt" ] || { echo "no .mp4 files in $CLIPS"; exit 1; }
ffmpeg -y -loglevel error -f concat -safe 0 -i "$TMP/list.txt" -c:v libx264 -pix_fmt yuv420p -an "$TMP/master.mp4"

# 2. Sample rate that spreads COUNT frames evenly over the whole duration.
DUR="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$TMP/master.mp4")"
FPS="$(awk -v c="$COUNT" -v d="$DUR" 'BEGIN { printf "%.6f", c / d }')"

# 3. Extract, downsize, JPEG quality 3 (~85%).
mkdir -p "$OUT"
rm -f "$OUT"/frame_*.jpg
ffmpeg -y -loglevel error -i "$TMP/master.mp4" \
  -vf "fps=$FPS,scale=$WIDTH:-2" -frames:v "$COUNT" -q:v 3 "$OUT/frame_%04d.jpg"

N="$(ls "$OUT"/frame_*.jpg | wc -l | tr -d ' ')"
cp "$OUT/frame_0001.jpg" "$OUT/poster.jpg"
read -r W H < <(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0:s=' ' "$OUT/frame_0001.jpg")

# 4. Manifest the page reads on load.
cat > "$OUT/manifest.js" <<EOF
// Generated by higgsfield/extract-frames.sh from $(basename "$CLIPS") (${DUR}s).
window.FRESH_FRAMES = { count: $N, dir: "frames", pattern: "frame_{n}.jpg", pad: 4, width: $W, height: $H, focal: 0.6 };
EOF

echo "wrote $N frames (${W}x${H}) to $OUT"
